spring:
  datasource:
    driverParams: serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useSSL=false&verifyServerCertificate=false&autoReconnect=true&autoReconnectForPools=true&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 初始化大小，最小，最大
    maxActive: 20
    initialSize: 5
    minIdle: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # \u901A\u8FC7connectProperties\u5C5E\u6027\u6765\u6253\u5F00mergeSql\u529F\u80FD\uFF1B\u6162SQL\u8BB0\u5F55
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # \u5408\u5E76\u591A\u4E2ADruidDataSource\u7684\u76D1\u63A7\u6570\u636E
    # useGlobalDataSourceStat=true
    dbName: shirodemo
    url: jdbc:mysql://rm-bp196027c6l4cnh7vho.mysql.rds.aliyuncs.com/${spring.datasource.dbName}?${spring.datasource.driverParams}
    username: swb
    password: Qaz840068536

# mybatis \u914D\u7F6E
mybatis:
  mapper-locations: classpath*:mapper/**/**/*Mapper.xml
  type-aliases-package: com.swb.*.model
  config-location: classpath:mybatis.xml

# Logging configuration
logging:
  level:
    root: INFO
    org.springframework: INFO
    com.swb: DEBUG
  file:
    path: ./log

mybatis-plus:
  global-config:
    banner: false
    db-config:
      update-strategy: not_null
      insert-strategy: not_empty
      logic-delete-value: 1
      logic-not-delete-value: 0